---
- name: Setup OCP installation
  hosts: localhost
  gather_facts: no
  connection: local
  become: false

  vars_files:
    - ../vars/ocp.yml

  vars:
    base: ../sno_data/{{ lpar.name }}

  tasks:
  - name: Create directory for {{ lpar.name }} data
    ansible.builtin.file:
      path: "{{ base }}"
      state: directory
      mode: '0755'   

  - name: Create SSH key pair for OCP
    shell: ssh-keygen -q -t rsa -N "" -f {{ base }}/ocp-rsa <<< y

  - name: Read public key
    set_fact:
      pubkey: "{{ lookup('file', '{{ base }}/ocp-rsa.pub') }}"

  - name: Remove setup directory
    ansible.builtin.file:
      path: "{{ base }}/setup"
      state: absent

  - name: Create setup directory
    ansible.builtin.file:
      path: "{{ base }}/setup"
      state: directory
      mode: '0755'

  - name: Load pull secret
    set_fact:
      pullsecret: "{{ lookup('file', '../vars/pullsecret')|string }}"

  - name: Create install-config.yaml
    template:
      src: ../templates/install_config.j2
      dest: "{{ base }}/setup/install-config.yaml"

  - name: Create ocp directory for binaries
    ansible.builtin.file:
      path: ../ocp
      state: directory
      mode: '0755'

  - name: Download OpenShift installer
    ansible.builtin.get_url:
      url: "{{ ocp_installer }}"
      dest:  ../ocp/openshift-installer-stable.tgz

  - name: Unpack OpenShift installer
    command: tar -xf openshift-installer-stable.tgz
    args:
      chdir: ../ocp
      creates: ../ocp/openshift-install

  - name: Create install-config.yaml
    template: 
      src: ../templates/install_config.j2
      dest: "{{ base }}/setup/install-config.yaml"

  - name: Create ignition config
    command:  ../ocp/openshift-install --dir {{ base }}/setup create single-node-ignition-config

  



