---
- name: Start installation
  hosts: localhost
  gather_facts: no
  collections:
      - ibm.power_hmc

  connection: local
  become: false

  vars_files:
    - ../vars/hmcs.yml
    - ../vars/network.yml
    - ../vars/ocp.yml

  tasks:
  - name: Compute boot disk device
    set_fact:
      boot_disk: "{{ '/dev/disk/by-id/wwn-0x' + bootdiskwwn if bootdiskwwn is defined else '/dev/sda' }}"

  - name: Boot LPAR and start network installation
    hmc_command:
      hmc_host: '{{ hmc[lpar.hmc].ip }}'
      hmc_auth: "{{ hmc[lpar.hmc].hmc_auth }}"
      cmd: >
        lpar_netboot -x -f -t ent -s auto -d auto
        -S {{ bastion }}
        -G {{ sno_gateway }}
        -C {{ sno_ip }}
        -K {{ sno_netmask }}
        {{ lpar.name }}
        {{ lpar.profile | default('default_profile') }}
        {{ lpar.managed_system }}
    connection: local

  - name: Wait for SSH to be active
    shell: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ../sno_data/{{ lpar.name }}/ocp-rsa core@{{ sno_ip }} id
    connection: local
    register: result
    retries: 10
    delay: 30
    until: result.rc == 0

  - name: Check that we provided the right boot disk
    shell: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ../sno_data/{{ lpar.name }}/ocp-rsa core@{{ sno_ip }} ls {{ boot_disk }}
    connection: local

  - name: OCP BUG - set bootlist
    shell: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ../sno_data/{{ lpar.name }}/ocp-rsa core@{{ sno_ip }} "sudo bootlist -m normal {{ boot_disk }}"
    connection: local
